[package]
name = "thingy"
version = "0.1.0"
authors = ["nk"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
git2 = "0.13"
failure = "0.1"
chrono = "0.4"
tempfile = "3.1"
file-lock = "1.1"
